### ISSUE TITLE
New folder icons

### ISSUE THREAD

**Issue by larsenwork** [fontforge/YosemiForge#5]
I'm trying to add folder icons that are more inspired by the theme and not any operating system.

![ffgui](https://cloud.githubusercontent.com/assets/3859425/7244574/e1a879fa-e7dd-11e4-860f-3a428964b49d.png)

In use
![screen shot 2015-04-21 at 04 19 27](https://cloud.githubusercontent.com/assets/3859425/7244588/ef5d76cc-e7dd-11e4-9946-8677dd379dbc.png)

**Comment by fitojb** [comment]
These icons look great! Out of curiosity, what tool do you use to design them?

**Comment by larsenwork** [comment]
thx, the icons will soon be the default ones. I used affinity designer mostly - great tool for what it can do but it still lacks some features.
